### ISSUE TITLE
Add endpoint for angular demo

### ISSUE THREAD

**Issue by SafinRR** [gentics/mesh-angular-example#13]
Hello!
How to add custom endpoint for angular demo?

**Comment by Jotschi** [comment]
Hi,

that depends on what the endpoint should do. You could:

* Add a nodejs server which exposes your own custom API and hook it using a reverse proxy in a central web server.

* Create a dedicated standalone API server for your endpoints which can handle CORS. This way your app could run XHR to for example the domain api.yourdomain.tld that exposes your API server.

* Create a mesh plugin and deploy it in Gentics Mesh. I would only use this for endpoints which provide additional functionality which heavily relies on the content of the headless CMS.
