### ISSUE TITLE
The big call to action button on the demo site does not work - Unbreakable links?

### ISSUE THREAD

**Issue by supersexy** [gentics/mesh-angular-example#14]
Well, I am just trying to understand this project and if it is still maintained and alive.

The big blue button labeled "Learn more" on the [demo] site(https://demo.getmesh.io/demo/) - the only big blue button - leads to a [404](https://getmesh.io/docs/beta/getting-started.html). 

But your project [features description](https://getmesh.io/features/) contains very prominently something about "Unbreakable links"... wtf?

Now I am asking myself: 
* does the project not deliver on its promises?
* why would anyone publish a demo for a project with an "unbreakable links" feature that contains one big button that leads to a broken link?
* is this project not maintained at all?
* what other kind of problems can users expect if we find such a thing on the frontdoor?

May I suggest you should pay more attention to your demo websites, as this is something your potential new users will see very early on in the expierence with your product, and probably leave it after seeing this. Also maybe it would be a good idea to use some old school cli link checker tool.

**Comment by Jotschi** [comment]
Thanks for your feedback. I have fixed the broken link.
